
# Options related to mob spawning
# Whether or not the mob will spawn naturally in the biomes defined in json/[mobName]-spawn.json
# Whether or not the mob will spawn when breaking blocks defined in json/[mobName]-spawn.json
# Whether or not the mob will spawn when killing entities defined in json/[mobName]-spawn.json
[MobSpawning]

	[MobSpawning.desert_mojo]
		"Desert Mojo Breaking Block Spawn " = true
		"Desert Mojo Killing Entity Spawn " = true
		"Desert Mojo Natural Spawn " = true

	[MobSpawning.forest_mojo]
		"Forest Mojo Breaking Block Spawn " = true
		"Forest Mojo Killing Entity Spawn " = true
		"Forest Mojo Natural Spawn " = true

	[MobSpawning.hound]
		"Hound Breaking Block Spawn " = true
		"Hound Killing Entity Spawn " = true
		"Hound Natural Spawn " = true

	[MobSpawning.Scarecrow]
		"Scarecrow Breaking Block Spawn " = true
		"Scarecrow Killing Entity Spawn " = true
		"Scarecrow Natural Spawn " = true

	[MobSpawning.scorpion]
		"Scorpion Breaking Block Spawn " = true
		"Scorpion Killing Entity Spawn " = true
		"Scorpion Natural Spawn " = true

	[MobSpawning.scorpion_baby]
		"Baby Scorpion Breaking Block Spawn " = true
		"Baby Scorpion Killing Entity Spawn " = true
		"Baby Scorpion Natural Spawn " = true

	[MobSpawning.wisp]
		"Wisp Breaking Block Spawn " = true
		"Wisp Killing Entity Spawn " = true
		"Wisp Purse Xp Reward Range " = [30, 30]
		"Wisp Natural Spawn " = true

	[MobSpawning.nether_wisp]
		"Nether Wisp Breaking Block Spawn " = true
		"Nether Wisp Killing Entity Spawn " = true
		"Nether Wisp Purse Xp Reward Range " = [80, 80]
		"Nether Wisp Natural Spawn " = true

	[MobSpawning.ender_wisp]
		"Ender Wisp Breaking Block Spawn " = true
		"Ender Wisp Killing Entity Spawn " = true
		"Ender Wisp Purse Xp Reward Range " = [240, 240]
		"Ender Wisp Natural Spawn " = true

	[MobSpawning.corpse_eater]
		"Corpse Eater Breaking Block Spawn " = true
		"Corpse Eater Killing Entity Spawn " = true
		"Corpse Eater Natural Spawn " = true

	[MobSpawning.peacock_spider]
		"Peacock Spider Breaking Block Spawn " = true
		"Peacock Spider Killing Entity Spawn " = true
		"Peacock Spider Natural Spawn " = true

	[MobSpawning.bullfrog]
		"Bullfrog Breaking Block Spawn " = true
		"Bullfrog Killing Entity Spawn " = true
		"Bullfrog Natural Spawn " = true

